{% set sdata = load_setup_py_data() %}
{% set name = "doit" %}

package:
  name: '{{ name }}'
  version: '{{ sdata['version'] }}'

source:
  path: ..

build:
#  noarch: python
  entry_points:
    - doit = doit.__main__:main
  script: python setup.py install  --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - cloudpickle
    - macfsevents  # [osx]
    - pyinotify  # [linux]

test:
  imports:
    - doit
  commands:
    - doit --help

about:
  home: sdata['url']
  license: sdata['license']
  summary: sdata['description']
  description: sdata['long_description']
